### PR TITLE
:sparkle: list of the call done by the postman

### PR DESCRIPTION
**Pull request by AlviseSembenico**

### CODE REVIEW

**Comment by alextreme** [comment]
Looks good, however as mentioned I'd like to see the calls on the server-run detail-view instead of in a separate view. 

We're making things complicated enough as is :)

**Comment by AlviseSembenico** [comment]
Updated as requested

**Comment by alextreme** [comment]
Thanks! Could you write tests for these changes? Lets start following our best practice of including code and tests in each PR

**Comment by AlviseSembenico** [comment]
Updated

**Pull request merged**
